import type { Prisma } from "@prisma/client";

export const CUSTOMERS_PAGE_SIZE = 10;

export const CUSTOMER_LIST_SELECT = {
  id: true,
  farmerName: true,
  changedFarmerName: true,
  vendorCode: true,
  surveyNo: true,
  newSurveyNo: true,
  rtcExtentAcre: true,
  rtcExtentGunta: true,
  rtcAKharab: true,
  rtcBKharab: true,
  balanceExtentAcre: true,
  balanceExtentGunta: true,
  leaseExtentAcre: true,
  leaseExtentGunta: true,
  totalGunta: true,
  totalCents: true,
  rentPerAcre: true,
  noOfYears: true,
  rentAmount: true,
  aesAdvanceDate: true,
  aesAdvanceChequeNo: true,
  aesAdvanceChequeAmount: true,
  aesAdvanceBankName: true,
  balanceRentAmount: true,
  tdsAmount: true,
  bankLoanDdDate: true,
  loanAmount: true,
  bankLoanDdNo: true,
  bankLoanBankName: true,
  rentalDdDate: true,
  leaseAmount: true,
  rentalDdChequeNo: true,
  rentalDdBankName: true,
  rentalDdPart1Date: true,
  rentalDdPart1Amount: true,
  rentalDdPart1ChequeNo: true,
  rentalDdPart1BankName: true,
  receivedDate: true,
  balanceRentChequeNo: true,
  receivedNeftAmount: true,
  shortageChequeAmount: true,
  shortageDate: true,
  shortageChequeNo: true,
  shortageBankName: true,
  shortageNote: true,
  shortageAmountSecondTime: true,
  shortageSecondDate: true,
  shortageSecondChequeNo: true,
  shortageSecondBankName: true,
  shortageThirdChequeAmount: true,
  shortageThirdDate: true,
  shortageThirdChequeNo: true,
  shortageThirdBankName: true,
  shortageAmountTotal: true,
  atlTotal: true,
  paoTotal: true,
  landConversion: true,
  otherRecoveries: true,
  podiFee: true,
  leaseDeedStampDuty: true,
  leaseDeedRegCharges: true,
  totalGovtFee: true,
  debitNoteNo: true,
  debitNoteAmount: true,
  balanceReceivable: true,
  otherCharges: true,
  cropCompensation: true,
  notes: true,
} as const;

export function customerListWhere(query: string): Prisma.CustomerWhereInput | undefined {
  const q = query.trim();
  if (!q) return undefined;
  return { farmerName: { contains: q, mode: "insensitive" } };
}
