CREATE TABLE "debit_notes" (
  "id" SERIAL PRIMARY KEY,
  "type" TEXT NOT NULL,
  "customerId" INTEGER NOT NULL REFERENCES "gst_customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "debitNoteNo" TEXT NOT NULL UNIQUE,
  "date" TEXT NOT NULL,
  "district" TEXT,
  "taluk" TEXT,
  "village" TEXT,
  "hobbli" TEXT,
  "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "gst" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "remarks" TEXT,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "debit_note_items" (
  "id" SERIAL PRIMARY KEY,
  "debitNoteId" INTEGER NOT NULL REFERENCES "debit_notes"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "farmerId" INTEGER,
  "farmerName" TEXT,
  "surveyNo" TEXT,
  "acres" DOUBLE PRECISION,
  "guntas" DOUBLE PRECISION,
  "rtcAcre" DOUBLE PRECISION,
  "rtcGunta" DOUBLE PRECISION,
  "leaseAcre" DOUBLE PRECISION,
  "leaseGunta" DOUBLE PRECISION,
  "landConversionFee" DOUBLE PRECISION,
  "podiFee" DOUBLE PRECISION,
  "recoveryFee" DOUBLE PRECISION,
  "atlCharges" DOUBLE PRECISION,
  "poaCharges" DOUBLE PRECISION,
  "chequePart1Amount" DOUBLE PRECISION,
  "chequePart1Date" TEXT,
  "chequePart1No" TEXT,
  "chequePart1BankName" TEXT,
  "chequePart2Amount" DOUBLE PRECISION,
  "chequePart2Date" TEXT,
  "chequePart2No" TEXT,
  "chequePart2BankName" TEXT,
  "remarks" TEXT,
  "total" DOUBLE PRECISION NOT NULL DEFAULT 0
);
